jwt:
  secret: 'uh912wu91212u12ada9812819221cdbuawd128701230jsiw012811213121sh1s2'

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal
    hikari:
      username: root
      password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  sql:
#    init:
#      password:
#      username: root

